### PR TITLE
Strip static libraries as well

### LINKED ISSUE #7: pacman-msys2 doesn't strip static libraries (archives)
Looking at https://github.com/msys2/msys2-pacman/blob/msys2-v6.0.1/scripts/libmakepkg/tidy/strip.sh.in#L204, It looks like pacman doesn't strip archives `application/x-archive`

Edit: They were stripped before upgrading to pacman 6.0
see: https://github.com/msys2/msys2-pacman/blob/msys2-v5.2.2/scripts/libmakepkg/tidy/strip.sh.in#L187

### PR DESCRIPTION
**Pull request by MehdiChinoune**
Fixes #7

### CODE REVIEW

**Comment by mati865** [comment]
I assume you have tested this because binutils used to break static libs when stripping them in the past.

**Comment by MehdiChinoune** [comment]
> I assume you have tested this because binutils used to break static libs when stripping them in the past.

No, I didn't. I thought the maintainers forgot to strip them (as they got stripped on Arch).
Did binutils used to break them on every platform or on MinGW-w64? if the first then many Linux distributions strip them without problem

**Comment by mati865** [comment]
I have rarely seen this issue on Linux but I wasn't using static libs a lot.
On Windows though it was quite common to the point I stopped stripping static libraries there. No idea about current state because I don't develop for Windows any more.

**Comment by MehdiChinoune** [comment]
The staticlibs were stripped before upgrading to pacman 6.0
see: https://github.com/msys2/msys2-pacman/blob/msys2-v5.2.2/scripts/libmakepkg/tidy/strip.sh.in#L187

**Comment by lazka** [comment]
thanks, I probably missed it during the rebase

**Pull request merged**
